import { StockItem, PlanItem, Group, AIPlanProposal } from '@/types';

// グループ情報
export interface GroupInfo {
  id: Group;
  name: string;
  icon: string;
  members: { id: string; name: string }[];
}

export const MOCK_GROUPS: GroupInfo[] = [
  {
    id: 'self',
    name: '自分だけ',
    icon: '📝',
    members: [
      { id: 'me', name: '自分' },
    ],
  },
  {
    id: 'family',
    name: '家族',
    icon: '👨‍👩‍👧',
    members: [
      { id: 'me', name: '自分' },
      { id: 'wife', name: '妻' },
      { id: 'child', name: '子' },
    ],
  },
  {
    id: 'friends',
    name: '高校の友達',
    icon: '🍺',
    members: [
      { id: 'me', name: '自分' },
      { id: 'tanaka', name: '田中' },
      { id: 'suzuki', name: '鈴木' },
      { id: 'sato', name: '佐藤' },
    ],
  },
  {
    id: 'work',
    name: '会社',
    icon: '💼',
    members: [
      { id: 'me', name: '自分' },
      { id: 'colleague_a', name: '同僚A' },
      { id: 'colleague_b', name: '同僚B' },
      { id: 'boss', name: '部長' },
    ],
  },
];

// 空き日データ
export interface AvailableDate {
  groupId: Group;
  userId: string;
  date: string; // YYYY-MM-DD
}

export const MOCK_AVAILABLE_DATES: AvailableDate[] = [
  // 家族
  { groupId: 'family', userId: 'me', date: '2025-01-18' },
  { groupId: 'family', userId: 'me', date: '2025-01-19' },
  { groupId: 'family', userId: 'me', date: '2025-01-25' },
  { groupId: 'family', userId: 'wife', date: '2025-01-18' },
  { groupId: 'family', userId: 'wife', date: '2025-01-25' },
  { groupId: 'family', userId: 'child', date: '2025-01-18' },
  { groupId: 'family', userId: 'child', date: '2025-01-19' },
  { groupId: 'family', userId: 'child', date: '2025-01-25' },
  // 友達
  { groupId: 'friends', userId: 'me', date: '2025-01-25' },
  { groupId: 'friends', userId: 'tanaka', date: '2025-01-25' },
  { groupId: 'friends', userId: 'suzuki', date: '2025-01-25' },
  { groupId: 'friends', userId: 'suzuki', date: '2025-02-01' },
];

// 個人ストック（自分だけ）
export const MOCK_PERSONAL_STOCKS: StockItem[] = [
  {
    id: 'p1',
    userId: 'me',
    title: 'サウナの聖地「しきじ」',
    category: 'outing',
    location: '静岡',
    imageUrl: 'https://images.unsplash.com/photo-1540518614846-7eded433c457?auto=format&fit=crop&q=80&w=400',
    user: '自分',
    group: 'self',
    date: '2024-01-10',
    status: 'active',
    createdAt: '2024-01-10T10:00:00Z',
    wantToGoCount: 0,
    wantToGoUsers: [],
    isRead: true,
  },
  {
    id: 'p2',
    userId: 'me',
    title: '話題のラーメン屋「一蘭」',
    category: 'gourmet',
    location: '福岡・天神',
    imageUrl: 'https://images.unsplash.com/photo-1557872943-16a5ac26437e?auto=format&fit=crop&q=80&w=400',
    user: '自分',
    group: 'self',
    date: '2024-01-08',
    status: 'active',
    createdAt: '2024-01-08T10:00:00Z',
    wantToGoCount: 0,
    wantToGoUsers: [],
    isRead: true,
  },
  {
    id: 'p3',
    userId: 'me',
    title: 'チームラボプラネッツ',
    category: 'event',
    location: '東京・豊洲',
    imageUrl: 'https://images.unsplash.com/photo-1549490349-8643362247b5?auto=format&fit=crop&q=80&w=400',
    user: '自分',
    group: 'self',
    date: '2024-01-05',
    status: 'active',
    createdAt: '2024-01-05T10:00:00Z',
    wantToGoCount: 0,
    wantToGoUsers: [],
    isRead: true,
  },
  {
    id: 'p4',
    userId: 'me',
    title: '金沢21世紀美術館',
    category: 'outing',
    location: '金沢',
    imageUrl: 'https://images.unsplash.com/photo-1518998053901-5348d3961a04?auto=format&fit=crop&q=80&w=400',
    user: '自分',
    group: 'self',
    date: '2024-01-03',
    status: 'active',
    createdAt: '2024-01-03T10:00:00Z',
    wantToGoCount: 0,
    wantToGoUsers: [],
    isRead: true,
  },
  {
    id: 'p5',
    userId: 'me',
    title: '道頓堀グルメ巡り',
    category: 'gourmet',
    location: '大阪・難波',
    imageUrl: 'https://images.unsplash.com/photo-1590559899731-a382839e5549?auto=format&fit=crop&q=80&w=400',
    user: '自分',
    group: 'self',
    date: '2024-01-01',
    status: 'active',
    createdAt: '2024-01-01T10:00:00Z',
    wantToGoCount: 0,
    wantToGoUsers: [],
    isRead: true,
  },
  {
    id: 'p6',
    userId: 'me',
    title: '厳島神社',
    category: 'travel',
    location: '広島',
    imageUrl: 'https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?auto=format&fit=crop&q=80&w=400',
    user: '自分',
    group: 'self',
    date: '2023-12-28',
    status: 'active',
    createdAt: '2023-12-28T10:00:00Z',
    wantToGoCount: 0,
    wantToGoUsers: [],
    isRead: true,
  },
  {
    id: 'p7',
    userId: 'me',
    title: '台北の夜市',
    category: 'gourmet',
    location: '台湾・台北',
    imageUrl: 'https://images.unsplash.com/photo-1470004914212-05527e49370b?auto=format&fit=crop&q=80&w=400',
    user: '自分',
    group: 'self',
    date: '2023-12-25',
    status: 'active',
    createdAt: '2023-12-25T10:00:00Z',
    wantToGoCount: 0,
    wantToGoUsers: [],
    isRead: true,
  },
  {
    id: 'p8',
    userId: 'me',
    title: 'ソウルでサムギョプサル',
    category: 'gourmet',
    location: '韓国・ソウル',
    imageUrl: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?auto=format&fit=crop&q=80&w=400',
    user: '自分',
    group: 'self',
    date: '2023-12-20',
    status: 'active',
    createdAt: '2023-12-20T10:00:00Z',
    wantToGoCount: 0,
    wantToGoUsers: [],
    isRead: true,
  },
  {
    id: 'p9',
    userId: 'me',
    title: 'ハワイでサーフィン',
    category: 'travel',
    location: 'ハワイ',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=400',
    user: '自分',
    group: 'self',
    date: '2023-12-15',
    status: 'active',
    createdAt: '2023-12-15T10:00:00Z',
    wantToGoCount: 0,
    wantToGoUsers: [],
    isRead: true,
  },
  {
    id: 'p10',
    userId: 'me',
    title: '札幌ラーメン横丁',
    category: 'gourmet',
    location: '北海道・札幌',
    imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&q=80&w=400',
    user: '自分',
    group: 'self',
    date: '2023-12-10',
    status: 'active',
    createdAt: '2023-12-10T10:00:00Z',
    wantToGoCount: 0,
    wantToGoUsers: [],
    isRead: true,
  },
];

export const MOCK_STOCKS: StockItem[] = [
  // 家族グループ
  {
    id: '1',
    userId: 'wife',
    title: '隠れ家イタリアン「Buono」',
    category: 'gourmet',
    location: '東京都世田谷区',
    imageUrl: 'https://images.unsplash.com/photo-1595295333158-4742f28fbd85?auto=format&fit=crop&q=80&w=400',
    user: '妻',
    group: 'family',
    date: '2023-10-25',
    status: 'active',
    createdAt: '2023-10-25T10:00:00Z',
    wantToGoCount: 2,
    wantToGoUsers: ['自分', '子'],
    isRead: true,
  },
  {
    id: '2',
    userId: 'me',
    title: '星空が見えるグランピング',
    category: 'travel',
    location: '山梨県',
    imageUrl: 'https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?auto=format&fit=crop&q=80&w=400',
    user: '自分',
    group: 'family',
    date: '2023-11-02',
    status: 'active',
    createdAt: '2023-11-02T10:00:00Z',
    wantToGoCount: 3,
    wantToGoUsers: ['自分', '妻', '子'],
    isRead: true,
  },
  {
    id: '4',
    userId: 'me',
    title: '話題の焼肉屋「炎」',
    category: 'gourmet',
    location: '渋谷区',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&q=80&w=400',
    user: '自分',
    group: 'family',
    date: '2023-11-10',
    status: 'active',
    createdAt: '2023-11-10T10:00:00Z',
    wantToGoCount: 1,
    wantToGoUsers: ['妻'],
    isRead: false,
  },
  {
    id: '5',
    userId: 'wife',
    title: '子連れOKの温泉旅館',
    category: 'travel',
    location: '箱根',
    imageUrl: 'https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&q=80&w=400',
    user: '妻',
    group: 'family',
    date: '2023-11-12',
    status: 'active',
    createdAt: '2023-11-12T10:00:00Z',
    wantToGoCount: 2,
    wantToGoUsers: ['自分', '子'],
    isRead: false,
  },
  // 友達グループ
  {
    id: '3',
    userId: 'tanaka',
    title: '激辛フェス 2024',
    category: 'event',
    location: '新宿公園',
    imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&q=80&w=400',
    user: '田中',
    group: 'friends',
    date: '2023-11-05',
    status: 'active',
    createdAt: '2023-11-05T10:00:00Z',
    wantToGoCount: 2,
    wantToGoUsers: ['自分', '鈴木'],
    isRead: true,
  },
  {
    id: '6',
    userId: 'suzuki',
    title: 'クラフトビール専門店',
    category: 'gourmet',
    location: '下北沢',
    imageUrl: 'https://images.unsplash.com/photo-1575037614876-c38a4d44f5b8?auto=format&fit=crop&q=80&w=400',
    user: '鈴木',
    group: 'friends',
    date: '2023-11-15',
    status: 'active',
    createdAt: '2023-11-15T10:00:00Z',
    wantToGoCount: 3,
    wantToGoUsers: ['自分', '田中', '佐藤'],
    isRead: false,
  },
  // 会社グループ
  {
    id: '7',
    userId: 'colleague_a',
    title: '個室居酒屋「和」',
    category: 'gourmet',
    location: '新橋',
    imageUrl: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&q=80&w=400',
    user: '同僚A',
    group: 'work',
    date: '2023-11-20',
    status: 'active',
    createdAt: '2023-11-20T10:00:00Z',
    wantToGoCount: 1,
    wantToGoUsers: ['同僚B'],
    isRead: true,
  },
];

export const MOCK_PLANS: PlanItem[] = [
  {
    id: 'p1',
    groupId: 'family',
    title: '秋の家族旅行 in 箱根',
    dateStart: '2025-01-18',
    dateEnd: '2025-01-19',
    status: 'planning',
    members: ['自分', '妻', '子'],
    itinerary: [
      { time: '10:00', title: '新宿駅 出発', description: 'ロマンスカー（前展望席確保済み）' },
      { time: '11:30', title: '箱根湯本 到着', description: '駅前で食べ歩き。手荷物は配送サービスへ。' },
      { time: '12:30', title: 'はつ花 そばランチ', description: 'ママのストックから採用！' },
      { time: '15:00', title: '彫刻の森美術館', description: '子供のアスレチックエリアあり' },
      { time: '17:00', title: '旅館チェックイン', description: '強羅花壇' },
    ],
    createdAt: '2023-11-01T10:00:00Z',
  },
  {
    id: 'p2',
    groupId: 'work',
    title: '会社の忘年会',
    dateStart: '2024-12-10',
    status: 'confirmed',
    members: ['同僚A', '同僚B', '部長'],
    createdAt: '2023-11-05T10:00:00Z',
  },
];

// AI提案プラン（グループごと）
export const MOCK_AI_PROPOSALS: Record<Group, AIPlanProposal[]> = {
  family: [
    {
      id: 'ai1',
      title: '箱根温泉＆グランピング',
      description: '妻のストック「温泉旅館」と自分の「グランピング」を組み合わせた2日間プラン',
      estimatedBudget: '約5万円/人',
      highlight: '子供も楽しめるアクティビティ付き',
      basedOnStocks: ['2', '5'],
    },
    {
      id: 'ai2',
      title: 'グルメ日帰りツアー',
      description: 'イタリアン「Buono」と焼肉「炎」を巡るグルメな1日',
      estimatedBudget: '約1.5万円/人',
      highlight: 'ランチ＆ディナーのダブル贅沢',
      basedOnStocks: ['1', '4'],
    },
    {
      id: 'ai3',
      title: '温泉でまったり週末',
      description: '箱根の温泉旅館で家族でゆっくり過ごす1泊2日',
      estimatedBudget: '約4万円/人',
      highlight: '部屋食プランで子連れも安心',
      basedOnStocks: ['5'],
    },
  ],
  friends: [
    {
      id: 'ai4',
      title: '激辛フェス＆クラフトビール',
      description: '激辛フェスでヒーヒーした後、下北沢でビールを堪能',
      estimatedBudget: '約8,000円/人',
      highlight: '辛さとビールの最高のマリアージュ',
      basedOnStocks: ['3', '6'],
    },
    {
      id: 'ai5',
      title: 'クラフトビール巡り',
      description: '下北沢のクラフトビール専門店でまったり飲み比べ',
      estimatedBudget: '約5,000円/人',
      highlight: '10種類以上のビールをテイスティング',
      basedOnStocks: ['6'],
    },
    {
      id: 'ai6',
      title: '激辛チャレンジ大会',
      description: '激辛フェスで誰が一番辛いものを食べられるか勝負',
      estimatedBudget: '約3,000円/人',
      highlight: '負けたら罰ゲームあり',
      basedOnStocks: ['3'],
    },
  ],
  work: [
    {
      id: 'ai7',
      title: '個室で本音トーク忘年会',
      description: '個室居酒屋「和」で1年の振り返りと来年の抱負を語る',
      estimatedBudget: '約6,000円/人',
      highlight: '完全個室でリラックス',
      basedOnStocks: ['7'],
    },
    {
      id: 'ai8',
      title: 'カジュアル飲み会',
      description: '気軽に集まれるサクッと2時間プラン',
      estimatedBudget: '約4,000円/人',
      highlight: '二次会も行ける時間設定',
      basedOnStocks: ['7'],
    },
    {
      id: 'ai9',
      title: 'チームビルディング飲み会',
      description: 'ゲームやクイズを交えた楽しい飲み会',
      estimatedBudget: '約5,500円/人',
      highlight: 'チーム対抗戦で盛り上がる',
      basedOnStocks: ['7'],
    },
  ],
  self: [],
  solo: [],
};
